wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1667072087.197886
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
arch:
  desc: null
  value: 2048,1024,512,248,512,1024,2048
batchsize:
  desc: null
  value: 128
count:
  desc: null
  value: 0
epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0003
optimizer_name:
  desc: null
  value: Adam
weightdecay:
  desc: null
  value: 0.0001
